### ISSUE TITLE
socializar modelo de datos de avances

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/avances_crud#2]
se requiere socializar el modelo de datos de avances realizado en el issue #1

**Comment by BOTOOM** [comment]
el dia 9 de febrero del 2021 se realizo la reunion de socializacion del modelo de datos el cual la cual fue [grabada](https://drive.google.com/file/d/1dcBM60gGSMJEZYvG0Nflcwc8j5nLU8_a/view) y estuvieron presentes @NRDaza @mcrubianot @corio27 @blacburn @fnrojash @steffanycruzs @danzola 

en esta reunion se socializo el siguiente modelo 

![modelo de datos de avances](https://user-images.githubusercontent.com/34488581/107062218-0ff75980-67a7-11eb-8321-10f1d9556328.png)

al finalizar la reunion quedaron lo siguientes puntos pendientes:

- [ ] todas las tablas parametricas desaparecerán (se dejara nota de ella y a donde se apunta) , estas tablas pasaran a ser registros en el api de parámetros
- [ ] se debe de agregar referencia al api de movimientos contables que se puede ver en la sección de reintegros y el paso de contabilización
- [ ] revisar el api de solicitudes con el fin de determinar si la tabla de `solicitud_avance` seguira en el modelo planteado

**Comment by NRDaza** [comment]
Se realizan los ajustes al modelo de datos según la reunión de socialización.

![Copy_of_New_Modelo_datos_Avance_Api_financiera-2021-02-10_18-27](https://user-images.githubusercontent.com/34488581/107591646-1b98b500-6bd9-11eb-952c-4b8c03b96699.png)

**Comment by BOTOOM** [comment]
@corio27 @blacburn @fnrojash @danzola se han realizado los respectivos cambios en el modelo de datos, pro favor revisar si consideran que se han cumplido y comentarlo en el presente issue
